### PR TITLE
Fix error in package command

### PR DESCRIPTION
**Pull request by n-rodriguez**
Fix https://github.com/vagrant-libvirt/vagrant-libvirt/issues/765

### CODE REVIEW

**Comment by n-rodriguez** [comment]
Hi! Actually this patch fixes a bug that happens with [test-kitchen](https://github.com/test-kitchen/test-kitchen) and [kitchen-vagrant](https://github.com/test-kitchen/kitchen-vagrant) : 

```
nicolas@nicolas-laptop:~/PROJECTS/saltstates$ kitchen package

-----> Package on sys-web-fb-stretch-amd64.
-----> Packaging remote instance
$$$$$$ Disable vagrant ssh key replacement to preserve the default key!
       Failed to load /etc/gemrc because it doesn't contain valid YAML hash
       ==> default: translation missing: en.vagrant_libvirt.package_domain
       qemu-img: Could not open '/var/lib/libvirt/images/sys-web-fb-stretch-amd64_default_1511452676_407e49c1588909474850.img': Failed to get shared "write" lock
       Is another process using the image?
       ==> default: Image has backing image, copying image and rebasing ...
       Nombre total d'octets écrits: 3045990400 (2,9GiB, 22MiB/s)
       /usr/lib/ruby/2.4.0/fileutils.rb:469:in `rename': No such file or directory @ rb_file_s_rename - (/home/nicolas/PROJECTS/saltstates/.kitchen/kitchen-vagrant/sys-web-fb-stretch-amd64/_tmp_package//home/nicolas/PROJECTS/saltstates/sys-web-fb-stretch-amd64.box, ..//home/nicolas/PROJECTS/saltstates/sys-web-fb-stretch-amd64.box) (Errno::ENOENT)
       	from /usr/lib/ruby/2.4.0/fileutils.rb:469:in `block in mv'
       	from /usr/lib/ruby/2.4.0/fileutils.rb:1461:in `block in fu_each_src_dest'
       	from /usr/lib/ruby/2.4.0/fileutils.rb:1477:in `fu_each_src_dest0'
       	from /usr/lib/ruby/2.4.0/fileutils.rb:1459:in `fu_each_src_dest'
       	from /usr/lib/ruby/2.4.0/fileutils.rb:458:in `mv'
```

kitchen-vagrant calls `package` command with the `--output` param : https://github.com/test-kitchen/kitchen-vagrant/blob/master/lib/kitchen/driver/vagrant.rb#L153.
It packages a new image in the current directory, not the temps dir, thus the error when moving the generated file.

**Comment by n-rodriguez** [comment]
I guess the patch is to check for file presence before moving it ;)

**Comment by infernix** [comment]
kitchen uses `        box_name = File.join(Dir.pwd, instance.name + ".box")` but we cannot rely on that. Users might not (and probably won't) specify a full path. So the proposed fix cannot be merged, but I'll take any patch that makes it work in these cases:

`vagrant package`
`vagrant package --output foo.box`
`vagrant package --output relative_path/foo.box`
`vagrant package --output /absolute_path/foo.box`

**Comment by n-rodriguez** [comment]
I've updated the patch, do you think it's mergeable?

**Comment by infernix** [comment]
This makes the code only more unreadable and I think it would fail with an absolute path?

**Comment by n-rodriguez** [comment]
> This makes the code only more unreadable and I think it would fail with an absolute path?

Ok, so what do you suggest to fix the bug?

**Comment by infernix** [comment]
> In general this code seems kludgy, but I think the right approach is to parse env['package.output'] into a boxpath and boxname variable (using File.split for example) and to use the full boxpath+boxname in the right places (such as the tar cvzf "#{boxpath}/#{boxname}")

**Pull request closed without merging**
