### PR TITLE
Floppy support

### PR DESCRIPTION
**Pull request by guss77**
Add support for attaching 1 or 2 floppy drives to the VM using "vfd" image files.

### CODE REVIEW

**Review by electrofelix — COMMENTED** [review]
The cdrom config function is doing the wrong thing unfortunately, as the number of devices should be checked in the validate function instead.

After moving, can you squash down the commits so it can be landed as a single commit.

**Comment by electrofelix** [comment]
@guss77 are you happy to update to do the number of floppy drives check in the validate function and provide a comment in the code where the check is done as to what is known about the limit?

**Comment by guss77** [comment]
Sorry for dropping out, I'll go over everything later this week.

**Comment by brianjmurrell** [comment]
Does this PR being open mean there is no support in vagrant-libvirt to be able to add a floppy drive to a box?

TBH, I don't really even care to have a floppy in my VM but it seems that `mdadm` tries to scan for floppies and hangs in doing so (apologies for the screenshot instead of text but I only had access to a console on this VM) when one isn't present:

image

So the path of least resistance seems to be to just give it a floppy to scan.  It seems the GParted folks discovered this also:

https://sourceforge.net/p/gparted/mailman/message/36899927/

It seems they disabled the floppy in the BIOS.  Is that an option with vagrant-libvirt?

**Comment by electrofelix** [comment]
@brianjmurrell unfortunately yes. Technically it should be possible to call attach-device after the domain is created but before it is started through the vagrant triggers via it's action hook mechanism. That would allow connecting floppy devices without them being in the original domain definition.

Alternatively if you could rebase this change, fix the couple of issues that I've commented on and submit as a new PR (could you keep the original author in place though so they get credited with the original work and add co-authored-by), I'd be happy to merge it

**Comment by electrofelix** [comment]
Going to handle the validation and device allocation separately afterwards for both cdrom and floppies together.

**Comment by electrofelix** [comment]
Just as a note here, libvirt only supports one floppy controller and it only supports 2 devices being attached, otherwise the following error will be emitted:
```
Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: internal error: Only 1 fdc controller is supported
```

**Pull request merged**
