### PR TITLE
Download images with libvirt instead of copying

### PR DESCRIPTION
**Pull request by ryanfitzsimon**
Packaging an existing vagrant environment relied on copying the backing
image. Users may not have permission to read this file despite being
able to interact with it through libvirt.

Use ruby-libvirt to download the image instead so any user with libvirt
access can run the package command.

### CODE REVIEW

**Comment by ryanfitzsimon** [comment]
I'll just start by letting you know I'm very new to ruby, so I'm not sure how much help I'll be for this.

Are there any existing integration tests for vagrant-libvirt? I've only seen unit tests so far.

This PR borrows heavily from `upload_image()` in [handle_box_image.rb](https://github.com/vagrant-libvirt/vagrant-libvirt/blob/5f7841ffffcdbdccd55f2065bef0ca16c2d79580/lib/vagrant-libvirt/action/handle_box_image.rb#L166). How is that currently tested?

**Comment by eighthave** [comment]
@uniqx is there anything in fdroid that could be repurposed as a test for this?

**Comment by uniqx** [comment]
I'm afraid we've got nothing that would work in a ruby based unit test. It's been a while since a last worked with this but my work looking at my work in [fdroidserver!589](https://gitlab.com/fdroid/fdroidserver/merge_requests/589) this is how I would do a test run:

    # define libvirt pool
    
    mkdir $$/test/pool/path
    cat << EOF > testpool.xml
    <pool type='dir'>
        <name>fdroid</name>
        <target>
            <path>$$/test/pool/path</path>
            <permissions>
                <mode>0770</mode>
                <owner>$$uid</owner>
                <group>$$gid</group>
            </permissions>
        </target>
    </pool>
    EOF
    sudo virsh pool-define testpool.xml
    
    # setup test vagrant vm
    
    cat << EOF > Vagrantfile
    Vagrant.configure("2") do |config|
      config.vm.box = "generic/alpine38"
      config.vm.provider :libvirt do |libvirt|
        libvirt.driver = "kvm"
        libvirt.host = "localhost"
        libvirt.uri = "qemu:///system"
      end
    end
    EOF

    vagrant up
    vagrant halt

    # take a look whether the VMs image was created with the correct file permissions

    ls -l /test/pool/path

**Comment by uniqx** [comment]
@eighthave I don't think so, we've got no ci tests for this yet. Should be easy on a libvirt enabled CI runner thou:

    vagrant init -m 'generic/alpine38'
    vagrant up --provider libvirt
    vagrant halt
    vagrant package --output test.box test

**Comment by mcandre** [comment]
Any movement on this? A manual test could serve, with coverage raised later

**Comment by eighthave** [comment]
I ran a manual test on Debian/buster using _vagrant_ from Debian/buster based on @uniqx's suggsted test script.  I verified that the box was not present in _/var/lib/libvirt/images_ before. running.

```console
root@gcc:~# git checkout ryanfitzsimon/master 
Previous HEAD position was e696032... Merge pull request #909 from davidscaife/redirfilter
HEAD is now at a61d2ab... Download images with libvirt instead of copying
root@gcc:~# git clean -fdx
root@gcc:~# rake build
vagrant-libvirt 0.0.43 built to pkg/vagrant-libvirt-0.0.43.gem.
vagrant-libvirt 0.0.43 built to pkg/vagrant-libvirt-0.0.43.gem.
root@gcc:~# vagrant plugin install vagrant-libvirt-0.0.43.gem
root@gcc:~# vagrant plugin install vagrant-libvirt-0.0.43.gem
Installing the 'vagrant-libvirt-0.0.43.gem' plugin. This can take a few minutes...
Fetching: formatador-0.2.5.gem (100%)
Fetching: excon-0.71.1.gem (100%)
Fetching: builder-3.2.4.gem (100%)
Fetching: fog-core-1.43.0.gem (100%)
Fetching: mini_portile2-2.4.0.gem (100%)
Fetching: nokogiri-1.10.7.gem (100%)
Building native extensions. This could take a while...
Fetching: multi_json-1.14.1.gem (100%)
Fetching: fog-json-1.2.0.gem (100%)
Fetching: fog-xml-0.1.3.gem (100%)
Fetching: ruby-libvirt-0.7.1.gem (100%)
Building native extensions. This could take a while...
Fetching: fog-libvirt-0.7.0.gem (100%)
Installed the plugin 'vagrant-libvirt (0.0.43)'!
root@gcc:~# vagrant init -m 'generic/alpine38'
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
root@gcc:~# vagrant up --provider libvirt
Bringing machine 'default' up with 'libvirt' provider...
==> default: Box 'generic/alpine38' could not be found. Attempting to find and install...
    default: Box Provider: libvirt
    default: Box Version: >= 0
==> default: Loading metadata for box 'generic/alpine38'
    default: URL: https://vagrantcloud.com/generic/alpine38
==> default: Adding box 'generic/alpine38' (v2.0.6) for provider: libvirt
    default: Downloading: https://vagrantcloud.com/generic/boxes/alpine38/versions/2.0.6/providers/libvirt.box
    default: Download redirected to host: vagrantcloud-files-production.s3.amazonaws.com
==> default: Successfully added box 'generic/alpine38' (v2.0.6) for 'libvirt'!
==> default: Uploading base box image as volume into libvirt storage...
Traceback (most recent call last):
	35: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.3/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
	34: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.3/lib/vagrant/machine.rb:194:in `action'
	33: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.3/lib/vagrant/machine.rb:194:in `call'
	32: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.3/lib/vagrant/environment.rb:614:in `lock'
	31: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.3/lib/vagrant/machine.rb:208:in `block in action'
	30: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.3/lib/vagrant/machine.rb:239:in `action_raw'
	29: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.3/lib/vagrant/action/runner.rb:66:in `run'
	28: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.3/lib/vagrant/util/busy.rb:19:in `busy'
	27: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.3/lib/vagrant/action/runner.rb:66:in `block in run'
	26: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.3/lib/vagrant/action/builder.rb:116:in `call'
	25: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.3/lib/vagrant/action/warden.rb:34:in `call'
	24: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.3/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	23: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.3/lib/vagrant/action/warden.rb:34:in `call'
	22: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.3/lib/vagrant/action/builtin/box_check_outdated.rb:31:in `call'
	21: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.3/lib/vagrant/action/warden.rb:34:in `call'
	20: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.3/lib/vagrant/action/builtin/call.rb:53:in `call'
	19: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.3/lib/vagrant/action/runner.rb:66:in `run'
	18: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.3/lib/vagrant/util/busy.rb:19:in `busy'
	17: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.3/lib/vagrant/action/runner.rb:66:in `block in run'
	16: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.3/lib/vagrant/action/builder.rb:116:in `call'
	15: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.3/lib/vagrant/action/warden.rb:34:in `call'
	14: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	13: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.3/lib/vagrant/action/warden.rb:34:in `call'
	12: from /root/.vagrant.d/gems/2.5.5/gems/vagrant-libvirt-0.0.43/lib/vagrant-libvirt/action/set_name_of_domain.rb:35:in `call'
	11: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.3/lib/vagrant/action/warden.rb:34:in `call'
	10: from /root/.vagrant.d/gems/2.5.5/gems/vagrant-libvirt-0.0.43/lib/vagrant-libvirt/action/handle_storage_pool.rb:57:in `call'
	 9: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.3/lib/vagrant/action/warden.rb:34:in `call'
	 8: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.3/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	 7: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.3/lib/vagrant/action/warden.rb:34:in `call'
	 6: from /root/.vagrant.d/gems/2.5.5/gems/vagrant-libvirt-0.0.43/lib/vagrant-libvirt/action/handle_box_image.rb:65:in `call'
	 5: from /root/.vagrant.d/gems/2.5.5/gems/vagrant-libvirt-0.0.43/lib/vagrant-libvirt/action/handle_box_image.rb:65:in `synchronize'
	 4: from /root/.vagrant.d/gems/2.5.5/gems/vagrant-libvirt-0.0.43/lib/vagrant-libvirt/action/handle_box_image.rb:107:in `block in call'
	 3: from /root/.vagrant.d/gems/2.5.5/gems/fog-core-1.43.0/lib/fog/core/collection.rb:51:in `create'
	 2: from /root/.vagrant.d/gems/2.5.5/gems/fog-libvirt-0.7.0/lib/fog/libvirt/models/compute/volume.rb:42:in `save'
	 1: from /root/.vagrant.d/gems/2.5.5/gems/fog-libvirt-0.7.0/lib/fog/libvirt/requests/compute/create_volume.rb:6:in `create_volume'
/root/.vagrant.d/gems/2.5.5/gems/fog-libvirt-0.7.0/lib/fog/libvirt/requests/compute/create_volume.rb:6:in `create_volume_xml': Call to virStorageVolCreateXML failed: storage volume 'generic-VAGRANTSLASH-alpine38_vagrant_box_image_2.0.6.img' exists already (Libvirt::Error)
```

**Comment by electrofelix** [comment]
@eighthave you're hitting an error on `vagrant up` which would be unrelated to this change. I've merged in more recent fixes to the PR and hope to merge it shortly so worth rechecking in a little while against master of this repo.

**Pull request merged**
