### PR TITLE
Make disabling and configuring memballoon possible

### PR DESCRIPTION
**Pull request by rubenk**
The memballoon settings didn't have any effect

### CODE REVIEW

**Comment by electrofelix** [comment]
You PR doesn't impact functionality, only reporting to the console whether the settings are enabled, which doesn't align with the summary and description provided, so I'm wondering what problem are you trying to solve.

**Comment by electrofelix** [comment]
Just re-read the code there, I see what it's doing now. Hasn't realise the variables were never defined

**Comment by rubenk** [comment]
The funny thing is there are unit tests for memballoon and they passed before this change. I haven't looked too deeply into why this is though.

**Comment by electrofelix** [comment]
They are setting the domain directly instead of setting the config object, definitely worth fixing up at some point

**Pull request merged**
