### PR TITLE
add disable dns feature issue #1521

### PR DESCRIPTION
**Pull request by johannes-enhance**
Allow disabling DNS from within the vagrant file so DNS does not conflict with local DNS installations.

### CODE REVIEW

**Comment by johannes-enhance** [comment]
Empty yet, but a good starting point.

**Comment by electrofelix** [comment]
@johannes-enhance are you still hoping to add support to disable the dns?

**Comment by johannes-enhance** [comment]
@electrofelix Yes, sorry I got bogged down with another issue. But I still intend to get this done.

**Comment by electrofelix** [comment]
Closing as assuming it's been dropped.

**Pull request closed without merging**
