### PR TITLE
Query host interfaces directly as libvirt may not include them

### PR DESCRIPTION
**Pull request by electrofelix**
On some distros the libvirt does not appear to always return all of the
host interfaces. Switch to using 'ip -j link show' to read them directly
from the system in order to ensure all devices are read.

Refactor the driver tests to better isolate between test setup for the
different sets of functions and avoid accidental setting of
configuration details that may not be obvious.

Fixes: #1624

### CODE REVIEW

**Comment by electrofelix** [comment]
@jamie01 are you in a position to apply this locally and give it a test run to check if it solves your problem before I merge it?

**Comment by jamie01** [comment]
> @jamie01 are you in a position to apply this locally and give it a test run to check if it solves your problem before I merge it?

Sure I can do that, will get back to you shortly - thanks for the changes!

**Comment by electrofelix** [comment]
@jamie01 to make things a little easier, I've added a job to build the gem for each pull request and make it available as an artifact so it can be downloaded and installed locally to help testing. https://github.com/vagrant-libvirt/vagrant-libvirt/actions/runs/3186087714 should contain a zip file containing the gem in question.

**Comment by jamie01** [comment]
Sorry got sidetracked yesterday - just gave it a go and it's erroring out for me with 
```
/home/jbarber/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.10.9.pre.22/lib/vagrant-libvirt/driver.rb:203:in `host_devices': undefined method `empty?' for nil:NilClass (NoMethodError)
```
It does also print a few `port class is NilClass` just before from your debug print.

I threw in a check for this and with that it all seems to work fine, the bridge is found and libvirt adds it into the networks

```
diff --git a/lib/vagrant-libvirt/driver.rb b/lib/vagrant-libvirt/driver.rb
index dc0d660..44e9103 100644
--- a/lib/vagrant-libvirt/driver.rb
+++ b/lib/vagrant-libvirt/driver.rb
@@ -200,7 +200,7 @@ module VagrantPlugins
       def host_devices
         @host_devices ||= begin
           cmd = []
-          if !@machine.provider_config.proxy_command.empty?
+          if @machine.provider_config.proxy_command && !@machine.provider_config.proxy_command.empty?
             cmd = ['ssh', @machine.provider_config.host]
             cmd += ['-p', @machine.provider_config.port.to_s] if @machine.provider_config.port
             cmd += ['-l', @machine.provider_config.username] if @machine.provider_config.username
```

```
$ sudo virsh domiflist bridge_error_node
 Interface   Type      Source            Model    MAC
---------------------------------------------------------------------
 vnet10003   network   vagrant-libvirt   virtio   52:54:00:77:08:d1
 vnet10004   bridge    br-mgmt           virtio   52:54:00:c3:98:4f
```

**Comment by electrofelix** [comment]
Thanks, I've removed the stray debug statement and updated the check.

**Pull request merged**
