### PR TITLE
fix a regression introduced in 546c98c

### PR DESCRIPTION
**Pull request by matt8754**

### CODE REVIEW

**Comment by matt8754** [comment]
This patch is aimed to fix #631 when creating a non-veryisolated network.

**Comment by pronix** [comment]
create test please with described behaviour

**Comment by matt8754** [comment]
I have been very busy since last month and will find out some time to create a test for this, even though I have noticed that the test coverage for this is so poor.

**Comment by infernix** [comment]
@pronix perhaps merge and add test later?

**Pull request merged**
