### PR TITLE
Allow non drvfs on wsl environment

### PR DESCRIPTION
**Pull request by y-hashida**
Hi Preact team!

I have been using vagrant-libvirt on a regular basis!

This time, I want to use this plugin in a wsl environment.

To do so, I need to set the wsl_allow_non_drvfs option to true, so I created this PR based on the official vagrant rsycn shared folder plugin example.

Official Example:

https://github.com/hashicorp/vagrant/blob/5b501a3fb05ed0ab16cf10991b3df9d231edb5cf/plugins/synced_folders/rsync/synced_folder.rb#L52-L56

(As a side note, systemd has recently been supported by wsl, so libvirt can be handled on wsl. Therefore, I would like to develop a combination of wsl and vagrant-libvirt.)

Thank you.

### CODE REVIEW

**Comment by electrofelix** [comment]
@y-hashida when you say you would like to use this on wsl, does this mean you're carrying the patch locally?

https://github.com/vagrant-libvirt/vagrant-libvirt/pull/1755#issuecomment-1646623032 combined with the install instructions at https://github.com/vagrant-libvirt/vagrant-libvirt#latest-development-version will allow you install a version of the plug-in with this patch applied if you'd like to test out further or just want to use it until a release is made with the patch applied.

**Comment by electrofelix** [comment]
Btw, it looks like this isn't quite up to date with the latest main but I'm not being allowed trigger an update branch on it. Would you mind rebasing or merging locally, or allow maintainers to update as the settings require that the pr is tested against the latest state of the target branch.

**Comment by y-hashida** [comment]
@electrofelix 
Thank you for your reply.

>when you say you would like to use this on wsl, does this mean you're carrying the patch locally?

As you said, we have confirmed that it works with WSL by applying the patch locally.

>Btw, it looks like this isn't quite up to date with the latest main but I'm not being allowed trigger an update branch on it.

I got it!
I merged the main branch into this branch.

**Comment by y-hashida** [comment]
@electrofelix 
Excuse me!

I have merged the latest version of the main branch into this branch!
Please check again once more!

**Comment by y-hashida** [comment]
@electrofelix

Excuse me for urging you again.
Would do you please take a look at this PR?

**Comment by y-hashida** [comment]
Thanks for the merge!

**Pull request merged**
