### PR TITLE
Fix static ipv6 ips on private networks

### PR DESCRIPTION
**Pull request by rubenk**
When the :ip is ipv6, set the 'static6' type, so that we select the
correct _static6.erb template to configure the interface in the guest.

With the following configuration, ipv6 works out of the box on CentOS 8:

  (1..2).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.hostname = "node#{i}"

      node.vm.network :private_network,
        :ip => "fc00::#{i+9}",
        :netmask => "64",
        :libvirt__dhcp_enabled => false,
        :libvirt__forward_mode => "veryisolated",
        :libvirt__network_name => "test"
    end
  end

Fixes: #914

### CODE REVIEW

**Comment by electrofelix** [comment]
That possibly fixes a few issues, I'll try to link them later so those that ran into the issue are alerted to the fix landing

**Comment by rubenk** [comment]
alright, thanks. I just tested this with Debian 11 and there it works as well.

Note that this only works if you set the netmask explicitly. It would be nice if we could parse :ip "fc00::10/64" as well.

**Comment by dereknola** [comment]
@electrofelix When is the next release coming out? I would love to have this PR, right now I am stuck manually building.

**Comment by electrofelix** [comment]
@dereknola finally done there this evening. I've been trying to wait until I thought I would have time to respond to any critical issues that might appear shortly after release.

**Pull request merged**
