### PR TITLE
Flag when source device for public network does not exist

### PR DESCRIPTION
**Pull request by electrofelix**
Detect when the device provided for connecting the VM to a public
network via the host does not exist and attempt to provide a useful
error message to give end users a hint of how to correct.

Fixes: #1477

### CODE REVIEW

**Comment by nexusVI** [comment]
My remote libvirt configuration doesn't work anymore: 
```
Libvirt Provider:
* network configuration 0 for machine default is a public_network referencing host device 'br0' which does not exist, consider adding ':dev => ....' referencing one of eth0
```

The device `br0` exists on the remote server but not on the server where i execute `vagrant`, this used to work before. 

Maybe related to this?

**Comment by electrofelix** [comment]
*sigh* yes, it is, sorry I missed making sure this was correct for remote

**Comment by electrofelix** [comment]
@nexusVI currently testing a fix which seems valid, but might take a little while before I can get it to push it up and land. In the mean time if you want to modify the code locally with the following, it should allow you to continue working:
```
@@ -1212,9 +1212,7 @@ module VagrantPlugins
 
       def host_devices
         @host_devices ||= begin
-          require 'socket'
-
-          Socket.getifaddrs.map { |iface| iface.name }.uniq.select do |dev|
+          machine.provider.driver.connection.client.list_all_interfaces().map { |iface| iface.name }.uniq.select do |dev|
             dev != "lo" && !@host_device_exclude_prefixes.any? { |exclude| dev.start_with?(exclude) }
           end
         end
```

Should also be possible to patch at the top of your Vagrantfile to contain the following to solve as well:
```
require 'vagrant-libvirt/config'

# since ruby doesn't seal classes, you can reopen and modify them
module VagrantPlugins
  module ProviderLibvirt
    class Config
      def host_devices
        @host_devices ||= begin
          machine.provider.driver.connection.client.list_all_interfaces().map { |iface| iface.name }.uniq.select do |dev|
            dev != "lo" && !@host_device_exclude_prefixes.any? { |exclude| dev.start_with?(exclude) }
          end
        end
      end
    end
  end
end

# place config after here
```

**Comment by electrofelix** [comment]
@nexusVI https://github.com/vagrant-libvirt/vagrant-libvirt/pull/1550 will be the fix

**Pull request merged**
